global:
  scrape_interval: 1s

# Remote-Write 수신만 사용하므로 scrape_configs는 비워두거나
# 자체 메트릭만 수집해도 무방
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'tracky-hub'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8082']
      

  - job_name: 'tracky-consumer'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8083']

  - job_name: 'k6'
    static_configs:
      - targets: ['k6:6565']
    metrics_path: '/metrics'